name: faim-hcs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python==3.9
  - conda-forge::mobie_utils==0.4.2
  - pip
  - click
  - cloudpickle
  - dask
  - fasteners
  - importlib-metadata
  - jinja2
  - locket
  - numcodecs
  - ome-zarr
  - pip:
    - git+https://github.com/fmi-faim/faim-hcs@v0.2.2
