name: faim-ipa
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python==3.11
  - conda-forge::mobie_utils==0.4.2
  - pip
  - click
  - cloudpickle
  - dask
  - fasteners
  - importlib-metadata
  - jinja2
  - locket
  - numcodecs
  - ome-zarr
